language: nix
nix: 2.1
sudo: true
matrix:
  include:
    - name: checkPhase - Nix 2
      script: nix-shell --run checkPhase --arg useNix1 false
    - name: checkPhase - Nix 1
      script: nix-shell --run checkPhase --arg useNix1 true
    - name: nix-build
      script: nix-build -A ofborg.rs
