language: nix
matrix:
  include:
  - script:
    - nix-shell --run 'cd ofborg && cargo test --lib -- --nocapture'
    - nix-shell --run 'cd ofborg && cargo test --lib -- --nocapture' --arg useNix1 true
