[package]
name = "ofborg"
version = "0.1.0"
authors = ["Graham Christensen <graham@grahamc.com>"]

[dependencies]
log = "0.3.8"
env_logger = "0.4.3"
amqp = "0.1.0"
md5 = "0.3.5"
fs2 = "0.4.2"
serde = "1.0"
serde_derive = "1.0"
serde_json = "1.0"
tempfile = "2.2.0"